# Generated by Django 6.1 on 2026-08-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='media/affiliation_symbols/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloraPropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='media/race_symbols/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmergeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=32, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('importance', models.CharField(blank=True, choices=[('protagonist', 'Protagonist'), ('supporting', 'Supporting'), ('npc', 'NPC')], max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('submerge_mutation_notes', models.TextField(blank=True, null=True)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media/character_display_images/')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='media/character_icon_images/')),
                ('expression', models.CharField(blank=True, choices=[('internal', 'Internal / Battery'), ('external', 'External / Projector'), ('latent', 'Latent / Dormant'), ('harmonic', 'Harmonic / Weaver')], max_length=32, null=True)),
                ('coherence_state', models.CharField(blank=True, choices=[('anchored', 'Anchored / Intact (100%)'), ('frayed', 'Frayed / Displaced'), ('fractured', 'Fractured / Distorted'), ('dissolved', 'Dissolved')], max_length=32, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.affiliation')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='core.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='race',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='races', to='core.region'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.affiliation')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.character')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.domain')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.region')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthplace_characters', to='core.region'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='affiliations', to='core.region'),
        ),
        migrations.AddField(
            model_name='character',
            name='story_fragments',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.storyfragment'),
        ),
        migrations.CreateModel(
            name='Submerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hazard_level', models.CharField(choices=[('SAFE', 'Safe / Stable'), ('MILD', 'Mild / Unpredictable'), ('HIGH', 'High Hazard'), ('LETHAL', 'Lethal / Reality Dissolving')], default='MILD', max_length=10)),
                ('influence_nature', models.CharField(choices=[('BENEFICIAL', 'Beneficial / Harvestable'), ('NEUTRAL', 'Neutral / Distorting'), ('DESTRUCTIVE', 'Destructive / Corrosive')], default='NEUTRAL', max_length=15)),
                ('description', models.TextField()),
                ('discovered_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.submergecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.TextField()),
                ('availability', models.CharField(choices=[('YEAR_ROUND', 'Year-round'), ('SPRING', 'Spring Bloom'), ('SUMMER', 'Summer Bloom'), ('AUTUMN', 'Autumn Fade'), ('WINTER', 'Winter Cryo'), ('ANOMALOUS', 'Anomalous Only (No Season)')], default='YEAR_ROUND', max_length=15)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('traits', models.ManyToManyField(blank=True, to='core.florapropertytag')),
                ('found_in_regions', models.ManyToManyField(blank=True, to='core.region')),
                ('exclusive_to_submerge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.submerge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('behavior', models.CharField(choices=[('DOCILE', 'Docile / Passive'), ('TERRITORIAL', 'Territorial'), ('AGGRESSIVE', 'Aggressive Predator'), ('ANOMALOUS', 'Anomalous / Unpredictable (Mimic, Phase-shifter)')], default='DOCILE', max_length=15)),
                ('about', models.TextField()),
                ('diet', models.CharField(choices=[('HERBIVORE', 'Herbivore'), ('CARNIVORE', 'Carnivore'), ('ESSENCE_EATER', 'Essence Eater')], default='HERBIVORE', max_length=100)),
                ('found_in_regions', models.ManyToManyField(blank=True, to='core.region')),
                ('exclusive_to_submerge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.submerge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='trivia_entries',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.triviaentry'),
        ),
    ]
