# Generated by Django 6.1 on 2026-08-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyfragment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/story_images/'),
        ),
        migrations.AddField(
            model_name='storyfragment',
            name='is_world_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triviaentry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
