# Generated by Django 6.1 on 2026-08-10 17:05

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fauna',
            name='about',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='about',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='about',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submerge',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
