# Generated by Django 6.1 on 2026-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fauna_about_alter_flora_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
