# Generated by Django 6.1 on 2026-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='symbol',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='media/affiliation_emblems/'),
        ),
        migrations.AddField(
            model_name='domain',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='media/domain_emblems/'),
        ),
    ]
