# Generated by Django 6.1 on 2026-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_affiliation_symbol_affiliation_emblem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='is_capital',
            field=models.BooleanField(default=False),
        ),
    ]
