# Generated by Django 6.1 on 2026-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_landmark_is_capital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='symbol',
        ),
        migrations.AddField(
            model_name='race',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='media/race_emblems/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/character_display_images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/character_icons/'),
        ),
    ]
