# Generated by Django 6.1 on 2026-08-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_race_symbol_race_emblem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='fauna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.fauna'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='flora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.flora'),
        ),
        migrations.AddField(
            model_name='storyfragment',
            name='fauna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.fauna'),
        ),
        migrations.AddField(
            model_name='storyfragment',
            name='flora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.flora'),
        ),
        migrations.AddField(
            model_name='triviaentry',
            name='fauna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_entries', to='core.fauna'),
        ),
        migrations.AddField(
            model_name='triviaentry',
            name='flora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_entries', to='core.flora'),
        ),
    ]
