# Generated by Django 6.1 on 2026-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galleryimage_fauna_galleryimage_flora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyfragment',
            name='teaser',
            field=models.CharField(blank=True, help_text='Short teaser text visible on the card.', max_length=200, null=True),
        ),
    ]
